[env]
MONGO_URI = "mongodb://localhost:27017/supchat?authSource=admin&directConnection=true&serverSelectionTimeoutMS=2000"
REDIS_URI = "redis://:password@localhost:6379"
FRONT_ACCOUNT_VALIDATE_URL = "http://localhost:5173/validate-account/{token}"
FRONT_ACCOUNT_FORGOT_PASSWORD_URL = "http://localhost:5173/forgot-password/{token}"
FRONT_ACCOUNT_RESET_PASSWORD_URL = "http://localhost:5173/reset-password/{token}"
FRONT_ACCOUNT_REGISTER_URL = "http://localhost:5173/register/{token}"
FRONT_ACCOUNT_LOGIN_URL = "http://localhost:5173/login"
FRONT_URL = "http://localhost:5173"
FRONT_WORKSPACE_INVITE_URL = "http://localhost:5173/workspace-invite-link/{token}"
HTTP_SERVER_PORT = "3000"
CORS_ORIGIN = "http://localhost:5173"
DOMAIN = "localhost"

[tasks.build-push]
run = "docker buildx build --platform=linux/amd64,linux/arm64 -t ghcr.io/supchat-lmrt/back-go:dev --push ."