name: "Test Suite"

on:
  workflow_call:

jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Mise en place de Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Mise en cache des modules Go
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Exécuter les tests Go
        run: go test ./... -v
