name: "Pipeline CI"

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  workflow_dispatch:

jobs:
  ci-run-tests:
    uses: ./.github/workflows/ci-test.yml


  ci-merge-dev:
      needs: ci-run-tests
      uses: ./.github/workflows/ci-merge.yml
      with:
        head_branch: test
        base_branch: main
      secrets:
        ORG_READ_TOKEN: ${{ secrets.ORG_READ_TOKEN }}

